# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$all"""

# Fill character (empty space) between the left and right prompt
[fill]
symbol = " "

[character]
success_symbol = "[➜](green)"
error_symbol = "[x](red)"

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = '%T'

[directory]
read_only = " 󰌾"
read_only_style = "red"
truncation_length = 5
truncate_to_repo = true
truncation_symbol = '.../'
format = "[$path]($style)[$read_only]($read_only_style) "


[docker_context]
symbol = " "

[git_branch]
style = "bold yellow"
symbol = " "
truncation_length = 10
truncation_symbol = ".../"

[git_commit]
commit_hash_length = 4
tag_symbol = "  "
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_status]
format = '([\[$ahead_behind $all_status\]]($style) )'
ahead = '⇡ ${count}'
style = "bold yellow"
diverged = '⇕⇡ ${ahead_count} ⇣ ${behind_count}'
behind = '⇣ ${count}'
conflicted = '󰨮'
stashed = 'stashed ${count}'
modified = "modified: ${count}"

[nodejs]
symbol = " "
format = "via [$symbol($version )]($style)"
style = "green"
detect_files = ["package.json", ".nvmrc", ".node-version", "pnpm-workspace.yaml"]
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx", "jsx", "vue"]
not_capable_style = "bold red"

[python]
symbol = " "

[cmd_duration]
min_time = 2_000
format = "took [$duration ]($style)"
style = "bold white"
