# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$all"""

# Fill character (empty space) between the left and right prompt
[fill]
symbol = " "

[character]
success_symbol = "[➜](white)"
error_symbol = "[➜](red)"

[directory]
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[docker_context]
symbol = " "

[git_branch]
style = "bold yellow"
symbol = " "
truncation_length = 20
truncation_symbol = "..."

[git_commit]
commit_hash_length = 4
tag_symbol = "  "
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = '⇡${count}'
style = "bold blue"
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
up_to_date = '✓'
conflicted = '󰨮'
stashed = '📦 \\$${count}'
modified = "modified ${count}"

[nodejs]
symbol = " "
format = "via [$symbol($version )]($style)"
style = "green"
detect_files = ["package.json", ".nvmrc", ".node-version", "pnpm-workspace.yaml"]
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx", "jsx", "vue"]
not_capable_style = "bold red"

[python]
symbol = " "

# Output the command duration if over 2 seconds
[cmd_duration]
min_time = 2_000
format = "took [$duration ]($style)"
style = "bold white"

# Customize the battery indicator
[battery]
format = "[$symbol $percentage]($style) "
empty_symbol = "🪫"
charging_symbol = '⚡️ '
full_symbol = '🔋'

[[battery.display]]
threshold = 20
style = 'red'